MCU = atmega32u4

BOOTLOADER = atmel-dfu

LTO_ENABLE = yes 
BOOTMAGIC_ENABLE = yes      
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
AUDIO_ENABLE = no
RGBLIGHT_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no
MUSIC_ENABLE = no
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
